#CodeDeploy main file
version: 0.0
os: linux
files:
  - source: target/aws-ec2-spring-api-0.1.jar
    destination: /home/ec2-user/moved-aws-ec2-spring-api-0.1.jar
hooks:
  BeforeInstall:
    - location: scripts/deploy/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/deploy/stop_server
      timeout: 300
      runas: root